### ISSUE TITLE
macOS Compatiblity

### ISSUE THREAD

**Issue by l33tmeatwad** [myrsloik/DotKill#1]
Add #include cstdlib for compatibility with clang in macOS.

**Comment by myrsloik** [comment]
Which header is missing?

**Comment by l33tmeatwad** [comment]
Sorry, the brackets made it invisible apparently...

**Comment by l33tmeatwad** [comment]
Sorry the brackets apparently made it invisible, wasn't expecting that.

**Comment by myrsloik** [comment]
Done
